package dev.olog.navigation.screens

enum class LibraryPage {
    LIBRARY_FOLDERS,
    LIBRARY_PLAYLISTS,
    LIBRARY_TRACKS,
    LIBRARY_ALBUMS,
    LIBRARY_ARTISTS,
    LIBRARY_GENRE,

    LIBRARY_PODCAST,
    LIBRARY_PODCAST_AUTHORS,
    LIBRARY_PODCAST_PLAYLISTS
}